### ISSUE TITLE
How to create data structure with if statements?

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/insect-injector#1]
Not sure how to properly define/ form my question but basically I'm struggling with the parts that involve if statements in this project. 

I was able to create the insects variable (array) and an object with properties name, img, family and size properties but got completely lost with last three properties ("Eats insects", "Eats dung", "Eats plants") and would appreciate some help. 

I know that I need to assign yes or no to `food.eatsInsects`, `food.eatsDung` and `food.eatsPlants` but how... feel like something to do with boolean but brain freeze right there!

@thomasjbradley

**Comment by thomasjbradley** [comment]
Boolean! Is the correct answer!

Something like this:

```js
food: {
  eatsInsects: false,
  eatsDung: true,
}
```
